### ISSUE TITLE
getallheaders in nginx service not found

### ISSUE THREAD

**Issue by dongm2ez** [jasny/sso#94] opened 2018-05-18 08:07 UTC
`getalheaders()` in nginx service not found

maye be you can use this code:

```php
if (!function_exists('getallheaders')) {
    function getallheaders() {
        foreach ($_SERVER as $name => $value) {
            if (substr($name, 0, 5) == 'HTTP_') {
                $headers[str_replace(' ', '-', ucwords(strtolower(str_replace('_', ' ', substr($name, 5)))))] = $value;
            }
        }
        return $headers;
    }
}
```

**Comment by jasny** [comment] 2020-07-15 12:32
Duplicate of #79

**Closed by jasny** 2020-07-15 12:32 UTC
